### ISSUE TITLE
Add warning when trying to open file/template with unsaved changes

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#100]
At the moment, if user opens a file or a template, their changes to the current file are immadiately gone. We should present a warning and let the user decide what to do. (Abandon changes, Save changes and continue or cancel)

**Comment by aQaTL** [comment]
I see to ways of implementing this: 
1. Just just create JDialog using JOptionPane;
2. Create custom JDialog window.
I created a something like a prototype (the first and easy option, so I didn't spend too much time on it):
![screenshot_20160425_192526](https://cloud.githubusercontent.com/assets/17130832/14792673/aa18c92e-0b1b-11e6-912b-e4eb8bdbb1be.png)
I tested it and it works good for me. 
If you expect something more advanced, tell me.
Changes commited to my repo. 

PS: I am not completely happy with saveFile() static method in SaveFile.java (had to create it to implement saving changes). Normally, I would move it to the EditorTopComponent class, but this class may become too large. Maybe I am thinking wrong and it's good. What do you think?

**Comment by sebbrudzinski** [comment]
@aQaTL  Concerning the approach, I think a simple JOptionPane is sufficient. I'd just extend the message to something along the lines: "You are about to close this file but have unsaved changes. Would you like to save the changes first?".

Concerning code, we should definitely not create some static methods in SaveFile nor in any classes that are registered via NetBeans Platform.  Moreover, there's no need to pass editor top component to SaveFile class, since it already retrieves one on its own (see TopComponentFactory that returns the singleton components). If there's some common logic that must be shared, I'd extract it to some separate util class.

Also, the code that will handle confirmation should also be as "standalone" as possible, so it can be easily used from other places in the application. I think in the future it will make sense to ask for the confirmation in more cases - for example when attempting to close the application or opening file from Dropbox.

**Comment by sebbrudzinski** [comment]
btw. creating a pull request when discussing the code is a good practice. I can leave some inline comments then, so you know which part I'm actually referring to.

**Comment by aQaTL** [comment]
@sebbrudzinski Message extended. Take a look:
![screenshot_20160428_213649](https://cloud.githubusercontent.com/assets/17130832/14898858/602ef872-0d89-11e6-9d4e-02060710ea4a.png)
I moved openFile, saveFile and saveFileAs methods to a separate class, and made access for them from etc. It should make it easier to use them from other places in the program (for example etc.fileAction().saveFile();).

Considering the code that handles warning displaying, I can move it to its own class, but I think that EditorTopComponent class is a good place. 

I also would like to make warnings when opening from Dropbox.

**Comment by sebbrudzinski** [comment]
@aQaTL  has fixed this
