### ISSUE TITLE
Adding "DownloadPDF" button in the "PDFPreview" panel

### ISSUE THREAD

**Issue by Amitbhave** [sebbrudzinski/Open-LaTeX-Studio#103]
Hi,

I was thinking about the following enhancement:

- Adding "DownloadPDF" button in the "PDFPreview" panel, so that if the user is satisfied, he can download the PDF right from there!

![preview-download](https://cloud.githubusercontent.com/assets/15723901/14908625/1b06fb78-0df7-11e6-9e83-36980062e72e.png)

- Let me know should I proceed working on this enhancement or not?

- If yes, I have to edit PDFViewerTopComponent.java to add new button, but i think it is not-editable. So can you please let me know what should be my approach?

Best Regards,
Amit

**Comment by sebbrudzinski** [comment]
There's already "Download PDF" icon in the toolbar (next to save/save as on your screenshot). I don't really think we need another one in the preview panel.

**Comment by Amitbhave** [comment]
Ok.. So I close this issue then. Let me know if there are some open issues on which beginner like me can work.;)

**Comment by sebbrudzinski** [comment]
@Amitbhave As a rule, we mark easier, good starter issues for new contributors with "community friendly" label. Take a look at open issues with that label that aren't taken and you are free to grab it.
