### ISSUE TITLE
Add Open LaTeX Studio Version Number to About Page

### ISSUE THREAD

**Issue by klhes** [sebbrudzinski/Open-LaTeX-Studio#106]
Add the version number to the About page.

**Comment by stefansbv** [comment]
In my proposed fix (mentioned above), the app version string is hardwired into the ApplicationUtils class, probably this is not the best approach, but it might work for now.

**Comment by sebbrudzinski** [comment]
Hello @stefansbv
Please open a pull request if you consider the issue finished. We will then proceed with review and/or testing.

**Comment by stefansbv** [comment]
Hello @sebbrudzinski 
Done, thank you.

**Comment by sebbrudzinski** [comment]
Fixed by @stefansbv  Thanks!
