### ISSUE TITLE
Add a Keyboard Shortcut for Toggling Comments

### ISSUE THREAD

**Issue by klhes** [sebbrudzinski/Open-LaTeX-Studio#107]
Add a keyboard shortcut for the Toggle Comment feature.

**Comment by hkumar6** [comment]
I was looking into how this could be done. I added the following line to the `ToggleComment` class that implements the `ActionListener`, taking `Ctrl-]` as the keyboard shortcut:
`@ActionReference(path = "Shortcuts", name = "D-CLOSE_BRACKET")`

But this does not work as I had expected. Any pointers on how to go about this?

**Comment by klhes** [comment]
I've very new to Maven, but I think you need to run a Maven build after making an update to the ActionReference annotations.  To run the Maven build in NetBeans, right-click on the OpenLaTeXStudio-parent project and select 'Clean and Build'.

After the Maven build is complete, run the application, and the shortcut should work.

**Comment by hkumar6** [comment]
Thank you @klhes . That worked.
What should we use as the shortcut here? I have added `Ctrl-]` for now.

**Comment by aQaTL** [comment]
How about `Ctrl + /` (slash)?

**Comment by sebbrudzinski** [comment]
Fixed by @hkumar6 
Thanks for answering the question @klhes  :)
