### ISSUE TITLE
Fix Toggle Comment Multi-Line Selection Behavior

### ISSUE THREAD

**Issue by klhes** [sebbrudzinski/Open-LaTeX-Studio#109]
Description: Toggling comments on a multi-line selection where lines have different comment statuses can result in odd behavior.

Steps to Recreate:
1. Open LaTex Studio
2. Open Existing Document
3. Highlight an uncommented line. There must be an uncommented line above it.
4. Click Toggle Comment.
5. Highlight a multi-line selection. The top line of the selection must be uncommented, and the selection must include the line selected in Steps 3 and 4.
6. Click Toggle Comment.
7. Notice that the commented line now begins with '%%'.

Expected Result:
One of two options:
1. Each line in the selection should be changed independently (If a line begins with '%', '%' should be removed. If a line does not begin with '%', '%' should be added.)
2. The entire selection should be changed based on the comment status of the first line. If comments are being toggled on, and a line in the selection is already commented, that line should not change.

Actual Result:
Note that the bottom line begins with '%%'. Since the top line of the selection was initially uncommented, a '%' was added to each line, regardless of whether the line already began with '%'.
```
    %  New features and fixes are added to the project on a regular basis. Currently, the application provides
    %%  a nifty code editor, with syntax highlight, basic code completion and live preview. You can also save your tex
```

**Comment by hkumar6** [comment]
I worked on this and found a fix. What should be the expected result: Option 1 or 2?

**Comment by sebbrudzinski** [comment]
@hkumar6 Can you open a pull request? I think option 1 doesn't make much sense. I can hardly imagine a situation where someone wants to "switch" lines that are commented. A more common situation is that someone wants to add more commented lines to already commented block of code, so option 2 seems like a good choice.

**Comment by sebbrudzinski** [comment]
Fixed by @hkumar6  Thanks!
