### ISSUE TITLE
Add Cancel Button to Choose Template Dialog

### ISSUE THREAD

**Issue by klhes** [sebbrudzinski/Open-LaTeX-Studio#112]
Add a Cancel button to the Choose Template dialog.

**Comment by sebbrudzinski** [comment]
I suppose you can still close the dialog using "X", but yes, let's add cancel as well.

**Comment by aQaTL** [comment]
Do you prefer cancel placement like this:
![cancelbuttoninopentemplate](https://cloud.githubusercontent.com/assets/17130832/16202789/86a3f522-3717-11e6-8c47-1c5827910bdb.png)
or like this:
![cancelbuttoninopentemplatev2](https://cloud.githubusercontent.com/assets/17130832/16202862/dbbde4fa-3717-11e6-962b-4de0038cc841.png)
or even somewhere else?

**Comment by aQaTL** [comment]
Done, as I said in [Issue #115](https://github.com/sebbrudzinski/Open-LaTeX-Studio/issues/115) I committed changes to my [pull request](https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/104). Once more, sorry for that.

And, here is the screenshot of actual look:
![smallerbutton](https://cloud.githubusercontent.com/assets/17130832/16204617/ffe973e6-371f-11e6-90fb-71d86ec596ed.png)

**Comment by aQaTL** [comment]
Oh, and some code of this issue was committed in "Issue #115 fixed commit". I know, I shouldn't work on everything at once.

**Comment by andyzen619** [comment]
Is this issue still open ?

**Comment by sebbrudzinski** [comment]
Fixed by @aQaTL
