### ISSUE TITLE
Open last file upon application startup

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#12]
When user opens the application, the last file that was worked on could get automatically opened. If the file does not exist anymore or if it's the first run, simply do not display anything.

**Comment by rbanna01** [comment]
Will take this if it's not already taken.

**Comment by sebbrudzinski** [comment]
@rbanna01 sure, feel free to take it

**Comment by rbanna01** [comment]
@sebbrudzinski Think it's ready for testing.

**Comment by sebbrudzinski** [comment]
@rbanna01 - where is the commit/commits? I cannot see any new pull request.

**Comment by rbanna01** [comment]
@sebbrudzinski Sorry, should be up now.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Does this item still exist? If this has not been resolved, may I take to work?  :D

**Comment by sebbrudzinski** [comment]
@WhiteHsu It still hasn't been implemented so you are free to take it

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Sorry to reply late because being so busy recently. I'll study codes and plan to start my work on this item on these days. Thank you.  :-)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
I'm investigating how to implement this feature and think there should be a place to keep information of the last opened file. After studying the class "OpenFile.java", I find we originally keep the "Last Dir" in the property file "settings.properties". So may I also keep the "Last Opened File" information here? Or do you recommend other ways to do this?
![image](https://cloud.githubusercontent.com/assets/7831418/15349474/b76a691a-1d05-11e6-9633-7de0ea43f66c.png)

**Comment by sebbrudzinski** [comment]
@WhiteHsu Sounds good to me

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Please kindly help review my codes and provide your valuable feedback. Thank you very much.  :-)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
I've updated codes again based on the latest project version. Please kindly help review. Thank you very much. :-)

**Comment by sebbrudzinski** [comment]
Fixed by @WhiteHsu   Thanks!
