### ISSUE TITLE
Update "Start the application" point of the "Setting up development env" wiki page

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#121]
The project structure have changed a bit after we have introduced Maven as our build framework. This should be reflected on our wiki page.

https://github.com/sebbrudzinski/Open-LaTeX-Studio/wiki/Setting-up-development-environment

**Comment by hkalalo** [comment]
Hi,
I see this is already open for a while. I would like to give it a try to update this.

**Comment by sebbrudzinski** [comment]
@hkalalo feel free to work on it!

**Comment by hkalalo** [comment]
Hi Sebastiaan @sebbrudzinski ,
I've edited the page with some adjustments that reflects the new structure and also took in #147 LaTeX distribution path. Can you verify/check and let me know this is what you expected to be changed?

thanks
Henri

**Comment by sebbrudzinski** [comment]
Hi @hkalalo 
thanks, I think it looks good. One thing that I would add is that if developers cannot see any changes in the application after they make changes in the code and build it, si because they need to run "clean" task on the root project before they build it. I'll also have to move the images to the gh-pages branch of Open LaTeX Studio, unless you want to open a pul request for that. Thanks for addressing the other issue too! I'll close it now.

**Comment by hkalalo** [comment]
Ok, great, glad I can help in this. I will add a note about the clean task.
About the pictures:yes, I tried to make a pull request for that, but didn't manage to do it since for the wiki only cloning to local is possible. Then I saw the previous picture were located at your github.io page, so I followed that approach for now. I will give it another try today or tomorrow to make a pull request.

**Comment by hkalalo** [comment]
Hi @sebbrudzinski Sebastian, 
I've added a small note about the clean task in case changes in the code are not reflected in the application after a rebuild. 
I've really tried to make a pull request for the images, but I can only clone the wiki locally and there is no option to fork or create a branch.
I can attach them here if that would make it easier, so you'd have them in one place. If you'd then move them and let me know the new location, I can adjust the hyperlinks in the page links to the new location.

**Comment by sebbrudzinski** [comment]
@hkalalo Actually you don't have to clone the whole wiki (and yes, I believe that indeed isn't possible). What you can however do is upload the images to the gh-pages branch (directory images). This will cause that they are available under "http://sebbrudzinski.github.io/Open-LaTeX-Studio/images/". You will have to open a pull request for that, since the "gh-pages" branch is protected, similar to master. If you encounter problems with that, let me know and I can just upload them myself.

**Comment by hkalalo** [comment]
hi @sebbrudzinski , sorry for the delay, I was distracted for a while by work . I've tried this again and also searched the web for more info. Either I must be doing something wrong or unlike the normal github repository the gh-pages (wiki's) don't allow pull requests (also see http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) 
If you would be able to upload the images, that would be great. let me know if I should adjust the hyperlinks in the md file.

**Comment by sebbrudzinski** [comment]
@hkalalo I think the "gh-pages" should have the pull requests enabled. Anyways, I can move them myself and will do so when time allows. I think we can consider this closed. Thanks @hkalalo !
