### ISSUE TITLE
Zoom not working right in /dev/new-pdfbox

### ISSUE THREAD

**Issue by KalKolberg** [sebbrudzinski/Open-LaTeX-Studio#130]
The zoom isn't working correctly in the new code.  It just gives a portion of the image so with 50% zoom it's just showing half the image of the page.  So basically it's not zooming at all it's cropping the page image.

**Comment by KalKolberg** [comment]
Seems to work fine if zoom is 100% or more, issue creeps in when the zoom is less than 100%

**Comment by KalKolberg** [comment]
Note that while the zoom has been reset to what worked before, that code also has a OutOfMemory Issue.  I'll look into scaling the image further and find out what can be done to fix the problem.  As of now the imaging < 100% zoom is working correctly.

**Comment by sebbrudzinski** [comment]
This should be working now.
