### ISSUE TITLE
No out of range checking on pages. /dev/new-pdfbox

### ISSUE THREAD

**Issue by KalKolberg** [sebbrudzinski/Open-LaTeX-Studio#131]
The new code doesn't check for page ranges.   

To Duplicate: open multi-page document click next a few times on the PDFViewer to advance the pagecount.
Load welcome.tex which is a single page file.   Error is generated as PDFPreviewBuilder tries to go to the current page number in a document where it does not exist.

**Comment by KalKolberg** [comment]
#137 adds bounds checking back into the system.

**Comment by sebbrudzinski** [comment]
This should be working now.
