### ISSUE TITLE
Text highlighting fails for \%

### ISSUE THREAD

**Issue by KalKolberg** [sebbrudzinski/Open-LaTeX-Studio#132]
Open document 
Insert \% into the document then put some text after that.
The editor incorrectly parses the % as a comment whereas it is actually placing an % into the text.

**Comment by KalKolberg** [comment]
The underlying code that does the syntax highlighting is org.fife.ui.esyntaxtextarea.  I've added an issue to their github repository at [https://github.com/bobbylight/RSyntaxTextArea/issues/193](https://github.com/bobbylight/RSyntaxTextArea/issues/193).  Not much more that can be done in our application.

**Comment by sebbrudzinski** [comment]
@KalKolberg Thank You for filling the bug against RSyntaxTextArea. It would be best if they managed to fix it so we can just bump the version when they release!

**Comment by sebbrudzinski** [comment]
It seems like they have fixed the issue on the master branch. We should consider updating, once they have a new release. Thanks again @KalKolberg !

**Comment by sebbrudzinski** [comment]
Fixed in 23836d6155b4fb688f250404237bd20f795c728f
