### ISSUE TITLE
Update wiki page with the LaTeX distribution’s path

### ISSUE THREAD

**Issue by evaliotiri** [sebbrudzinski/Open-LaTeX-Studio#147]
The setting of LaTeX distribution’s path which is not clearly defined in the wiki page “Setting up development environment”. Another user had the same problem and mentioned it in the [mailing list](https://groups.google.com/forum/#!searchin/open-latex-studio/latex$20distribution%7Csort:relevance/open-latex-studio/YPG79am3CxE/wCiK14Z6kgIJ).

 So, it would be helpful and practical the wiki page to be updated with that information.

**Comment by sebbrudzinski** [comment]
This should be clearly explained now. Closing.
