### ISSUE TITLE
More features on spell checking

### ISSUE THREAD

**Issue by WhiteHsu** [sebbrudzinski/Open-LaTeX-Studio#149]
To enhance the feature of spell checking, including:
1. Automatically execute spell checking instead of manual trigger.
2. Implement another separate thread for automatic spell checking.

P.S. For enhancement to select the highlight color, we'll create another ticket.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
In addition to the two features mentioned above, do you recommend more others?  :-)

**Comment by sebbrudzinski** [comment]
@WhiteHsu I think it would be great if the spell checking was happening in its own, separate thread. That way the application won't "hang" when the spel checking is being performed. This will be especially useful when the spell checking happens automatically. I think this could look very similar to how updating the PDF preview works, using the "dirty" flag. The PDF Preview thread checks every few seconds if the state is "dirty" and if so, it re-renders the preview. 

Moreover, I think it makes sense to have those two things as separate tickets. Also, selecting the highlight color is very low priority.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Thanks for your feedback. I've updated this ticket accordingly. If you think this new ticket description is OK, please assign this ticket to me, and I'll start to work on this. Thank you very much.  :-)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
If you think my modification on this task is OK, please assign this task to me, then I'm starting to my development. Thank you.  :-)

**Comment by sebbrudzinski** [comment]
@WhiteHsu Yes, this looks good. You are welcome to work on that. Sorry for late response, I'm travelling and have limited access.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
I've updated and checked in codes as the pull request:
https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/150

Please kindly help review and feedback. Thank you very much.  :-)

**Comment by sebbrudzinski** [comment]
Closing as fixed.
