### ISSUE TITLE
Comment out selected part of tex code

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#26]
Add a new menu option in the "Edit" section, that will allow to comment/uncomment currently selected part of the tex source code. A keyboard shortcut should be created to allow these operations as well.

**Comment by Labelpm** [comment]
Hi @sebbrudzinski, could you please add an example, how should look commented text  and provide the example of multi-selection 

Does it mean, you would like to add a comment sign at the beginning of the string ?

%Thanks for trying out the Open \LaTeX{} Studio - an Open Source \LaTeX{} editor.  
%Please note, that the

**Comment by sebbrudzinski** [comment]
@Labelpm  Yes, adding % at the beginning of each selected line should be sufficient for now. If 3 lines are selected - add % at the beggining of these 3 lines, if there's no selection, we should comment out a single line, where the cursor is currently placed. Note that the action should be surfaced in the menu and as a keyboard shortcut.

**Comment by Labelpm** [comment]
@Please check pull request

**Comment by hudsongeovane** [comment]
News about this?

**Comment by sebbrudzinski** [comment]
@hudsongeovane The pull request has been reviewed, but the feature does not work properly yet. See https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/50

**Comment by sebbrudzinski** [comment]
Fixed by @Labelpm
