### ISSUE TITLE
Better UI for Dropbox revisions

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#29]
When opening a file from the Dropbox account, a new window will become available at the bottom of the application, containing a list of dropbox revision. Currently the revision is represented as a long String, containing basic information about revision: id, date modified, size... it would be preferable to present the data in some kind of a table and make it more obvious, that double click will open a window with that revision.

**Comment by mylk13** [comment]
I will try to do this

**Comment by sebbrudzinski** [comment]
@mylk13 Awesome! In case of any questions or troubles, do not hesitate to ask us!

**Comment by mylk13** [comment]
//Previous comment accidentially deleted.

**Comment by mylk13** [comment]
Values of "dropbox.appKey" and "dropbox.appSecret"
in: "EditorModule\src\latexstudio\editor\resources\dropbox.properties" are null.
Trying to connect to dropbox throws an exception.

**Comment by sebbrudzinski** [comment]
You will need Dropbox developer account to connect to Dropbox. See our wiki: https://github.com/sebbrudzinski/Open-LaTeX-Studio/wiki#dropbox-collaboration-development

**Comment by sebbrudzinski** [comment]
Fixed by @mylk13, thanks :)
