### ISSUE TITLE
Incorrect labels for Open file window

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#30]
Description:
The Open file window does not have the correct labels. It can be mistaken for Save file window thus it can confuse the user.

Steps to Recreate:
1. Open LaTex Studio
2. Navigate to menu bar File > Open File

Expected Result:
The Open File window have the correct labels

Actual Result:
The Open File window have incorrect labels

Screenshot: 
Windows 7
![image](https://cloud.githubusercontent.com/assets/13062974/8477751/23f34812-20ff-11e5-98e5-3283bcf1656c.png)

Linux - Ubuntu 14.04.2
![image](https://cloud.githubusercontent.com/assets/13062974/8477806/9751ccc0-20ff-11e5-98a0-b40b3246760f.png)

**Comment by sebbrudzinski** [comment]
Labels have been fixed and should now display approperiately, depending on the selected action.

**Comment by LloydBG** [comment]
Issue is not 100% fixed. Linux environment still has the incorrect labels as seen in the screenshot.
