### ISSUE TITLE
The Math symbol-Integral sign is not being displayed in the pdf preview window

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#33]
Description:
The PDF preview window doesn't display the integral sign. When the tex file generates a PDF, the integral sign is displayed.

Steps to Recreate:
1. Open LaTex Studio
2. Open Existing Document 
3. type \usepackage{amsmath} in the preamble section of the document
4. At the body of the document type
\begin{equation*}
x = \int^0_5 y^2 +7
\end{equation*}

Expected Result:
The pdf preview window will display the whole equation including the integral sign

Actual Result:
The pdf preview window did not display the integral sign to complete the equation

Screenshot:
Windows 7
![image](https://cloud.githubusercontent.com/assets/13062974/8499676/c25b02e2-21c7-11e5-8d65-347b44cbde2b.png)
In the generated PDF the integral sign is displayed.
![image](https://cloud.githubusercontent.com/assets/13062974/8499688/dc0e807e-21c7-11e5-8182-7ebcb9547385.png)

**Comment by Labelpm** [comment]
Sign SUM not being displayed as well as an integral sign
Sum  $\sum_{n=1}^{\infty} 2^{-n} = 1$ inside text

**Comment by GaboFDC** [comment]
I was checking and it semss to be a buf in the PDPage.convertToImage so i reported this: https://issues.apache.org/jira/browse/PDFBOX-2915

**Comment by GaboFDC** [comment]
Also, while debugging made this change:

```diff
--- a/OpenLaTeXStudio/EditorModule/src/latexstudio/editor/pdf/PDFPreviewRefresher.java
+++ b/OpenLaTeXStudio/EditorModule/src/latexstudio/editor/pdf/PDFPreviewRefresher.java
@@ -11,6 +11,7 @@ import java.util.logging.Logger;
 import javax.swing.JPanel;
 import javax.swing.JScrollPane;
 import javax.swing.JViewport;
+import latexstudio.editor.ApplicationLogger;
 import latexstudio.editor.EditorTopComponent;
 import latexstudio.editor.files.FileService;
 import latexstudio.editor.runtime.CommandLineBuilder;
@@ -27,7 +28,7 @@ public class PDFPreviewRefresher implements Runnable {
     private final EditorTopComponent etc;
     private final PDFDisplay pdfDisplay;

-    private static final Logger LOGGER = Logger.getLogger(PDFPreviewRefresher.class.getName());
+       private static final ApplicationLogger LOGGER = new ApplicationLogger("Open LaTeX Studio");

     public PDFPreviewRefresher(JScrollPane jScrollPane, EditorTopComponent etc, PDFDisplay pdfDisplay) {
         this.jScrollPane = jScrollPane;
```

**Comment by sebbrudzinski** [comment]
It looks like this has been fixed in PDFBox 2.0.0 which is now released https://pdfbox.apache.org/index.html
We should consider migrating to new PDFBox.

**Comment by sebbrudzinski** [comment]
I've updated the pdfbox version we use to 2.0.0, however there are some issues. When scaling the image up, at some point the renderer throws OutOfMemoryError. If anyone is interested in trying to resolve that problem, the progress is on [dev/new-pdfbox](https://github.com/sebbrudzinski/Open-LaTeX-Studio/tree/dev/new-pdfbox) branch.

**Comment by KalKolberg** [comment]
Looks like the out of memory error is tied to the scaling not working.  The returned image expands in size until it's too large, not sure of the actual implementation.

**Comment by KalKolberg** [comment]
Looks like the old method for zooming had issues as well, still ongoing in order to generate a fix for the issue.

**Comment by sebbrudzinski** [comment]
Should be fixed by https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/140
