### ISSUE TITLE
Add "Save As" to the file menu

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#34]
Currently the save button always works as "save as", meaning that the user is forced to pick a location each time they want to save their changes. We should adjust this, so the save button saves the file that is currently worked on and the new "save as" option works as current "save".

**Comment by rbanna01** [comment]
I'm interested in giving this a shot.

**Comment by sebbrudzinski** [comment]
Sure! You are welcome to start working on this issue. In case of any questions or troubles, let us know here or via mailing list. Once you have finished the issue, create a pull request, so we can review this :)

**Comment by LloydBG** [comment]
@sebbrudzinski I tested rbanna01's pull request and It is working as expected. 'Save file' saves the current changes in the document. 'Save As' allows the user to save the file in different location and a warning dialog box is displayed when the user tries to overwrite an existing document.

**Comment by sebbrudzinski** [comment]
Fixed by @rbanna01 and @hudsongeovane
