### ISSUE TITLE
PDF preview window doesn't update after clicking the Undo/Redo button

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#37]
Description:
PDF preview window doesn't update after clicking the Undo/Redo button

Steps to Recreate:
1. Open LaTex Studio
2. Open a document to edit
3. Make changes to the document
4. Click the undo button

Expected Result:
The PDF preview window must be identical on the text displayed or written in the text editor window after clicking the Undo/Redo button

Actual Result:
The PDF preview window isn't identical on the text displayed or written in the text editor window after clicking the Undo/Redo button

Affected Environment:
Windows 7
Linux - Ubuntu 14.04.2

Screenshot:
Use welcome.tex to demonstrate the functionality of the undo button and make changes to the word "Welcome"
![image](https://cloud.githubusercontent.com/assets/13062974/8571182/b657e750-25b7-11e5-8b0d-f0a6b2a09427.png)
Delete the "come" in "Welcome"
![image](https://cloud.githubusercontent.com/assets/13062974/8571193/cbc5e5d8-25b7-11e5-8a95-554b3760eac1.png)
After clicking the undo button, the word "Wel" changed into "Welcome" which is the working as expected. While in the pdf preview window the word "Wel" didn't change
![image](https://cloud.githubusercontent.com/assets/13062974/8571200/d6490ce2-25b7-11e5-9210-c688ba56ad82.png)

**Comment by Labelpm** [comment]
Fixed, please pull from my repository
@LloydBG @sebbrudzinski

**Comment by LloydBG** [comment]
@sebbrudzinski @Labelpm 

Would I be able to test this if there is no pull request for this issue?

**Comment by sebbrudzinski** [comment]
@LloydBG This was a part of the pull request that has been merged in. It did fix the issue, but it was not a proper way to do so (basically sending preview refresh requests all the time). If Labelpm fixes this, it will be in a brand new pull request.

**Comment by LloydBG** [comment]
@sebbrudzinski This is fixed. Undo/Redo buttons are working as expected

**Comment by sebbrudzinski** [comment]
Thanks for testing this @LloydBG I've reviewed the code and tested the change. It looked good to me, so the pull request is now merged. Thanks for fixing this issue @Labelpm
