### ISSUE TITLE
Overwrite File feature

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#39]
The Open-LaTeX Studio doesn't have an overwrite feature for the pdf files generated by the user. Overwrite feature must have a pop-up warning to warn users that saving the file with the same File name in the directory will overwrite the existing pdf. This pop-up warning will also help users from accidentally overwriting their files.

**Comment by hudsongeovane** [comment]
I take this.

**Comment by sebbrudzinski** [comment]
Fixed by @hudsongeovane, thanks :)
