### ISSUE TITLE
Unable to Save file

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#43]
Description:
The user is unable to save a new file from the application. A dialog box with the message "File not found" is displayed.

Steps to Recreate:
1. Open Open-LaTeX-Studio
2. Save the Welcome.tex document
3. Give a new file name to the file (Name which still doesn't used in the current directory)
4. Click save button

Expected Result:
The file is saved inside the directory selected

Actual Result:
A dialog box appears informing the user that the file name specified can't be found, thus saving the file is unsuccessful

Affected Environment:
Windows 7
Linux - Ubuntu 14.04

Screenshots:
![11](https://cloud.githubusercontent.com/assets/13062974/8666201/79ce4622-2a20-11e5-9c3e-fecda1819606.png)

![22](https://cloud.githubusercontent.com/assets/13062974/8666202/7e6acc0a-2a20-11e5-81c5-946aea385e36.png)

**Comment by sebbrudzinski** [comment]
This is something that has been missed testing recent pull request. I'll try to submit fix to this quickly.

**Comment by sebbrudzinski** [comment]
This should be fixed now. @LloydBG could you verify this works as expected for various combinations? Saving/Opening files/Generating PDFs for files that doesn't/do exist. Thanks in advance!

**Comment by LloydBG** [comment]
@sebbrudzinski Retest passed! The user can now save new files and would not be able to open files which doesn't exist.
