### ISSUE TITLE
Improve setting LaTeX distribution path, by verifying whether pdflatex is present in the given directory

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#46]
Open LaTeX Studio makes extensive use of the pdflatex tool. This means that the usage of the editor is only possible if Open LateX Studio has got access to this tool. It is possible to set the path to the LaTeX distrubution (Tools -> options -> LaTeX), but this path is not verified in any way. We should verify the path pointed by the user and notify them, if the selected path does not contain pdflatex tool.

**Comment by hudsongeovane** [comment]
I have implemented the pdflatex.exe verification. I made some mistakes, but already fixed in pull request #52

**Comment by sebbrudzinski** [comment]
Fixed by @hudsongeovane, thanks :)
