### ISSUE TITLE
Add "View revision" button to dropbox revisions table

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#58]
Currently, the only way to view a dropbox revision is to double-click on the revision we want to view. It may not be clear for the users, that double click will show them the revision, therefore as an additional option we should expose a button, that says "view revision". A single click on the button should open the revision.

**Comment by glandre** [comment]
I'm going to start working on it.

**Comment by sebbrudzinski** [comment]
Fixed by @glandre Thank You :)
