### ISSUE TITLE
Fix checkstyle errors

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#59]
Checkstyle plugin has already been integrated with the build. We should now fix the issues that it is currently reporting. The checkstyle plugin can be run using the ant target, called "checkstyle". In NetBeans, this can be achieved right-clicking on the Important Files -> Build Script and selecting Run target -> checkstyle. The report will be generated in the Project directory and will be called "checkstyle-result"

**Comment by GaboFDC** [comment]
I tried, the build fails and the report show the lines to be fixed.
I can take this.

**Comment by sebbrudzinski** [comment]
Fixed by @GaboFDC  many thanks!
