### ISSUE TITLE
Remember last path

### ISSUE THREAD

**Issue by glandre** [sebbrudzinski/Open-LaTeX-Studio#63]
When a path is chosen one time (e.g., when saving a .tex file, or changing the LaTeX distribution directory) it could be remembered for the next time, so that the user saves time if he/she wants to save a new document in the directory previously used.

**Comment by mylk13** [comment]
I will try to do this one.

**Comment by glandre** [comment]
Hi Mateusz, I am already working on it.
Em 13/12/2015 08:18, "Mateusz Makowski" <notifications@github.com> escreveu:

**Comment by sebbrudzinski** [comment]
Fixed by @glandre Thanks!
