### ISSUE TITLE
Add keyboard shortcut for saving file

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#71]
We should add the support for ctrl+S shortcut, that saves the current file or opens a save as dialog, if no file was opened yet.

**Comment by sabbir044** [comment]
Hello sebbrudzinski, I want to complete this issue. 
I actually finished it and will do a pull request once you give me the permission.

**Comment by sebbrudzinski** [comment]
Hello @sabbir044 
Sure thing, go ahead and submit a pull request :) You do not require anyone's permission to do so.

**Comment by sebbrudzinski** [comment]
Fixed by @sabbir044  Thanks :)
