### ISSUE TITLE
NullPointerException on double click in Dropbox Revisions table

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#72]
Repro steps:
* Open application but do not open any remote Dropbox file
* In Window menu click on Dropbox Revisions, what opens a revision table at the bottom of the application
* Double click any row
* See exception 

Ideally, the table should not have any rows if no dropbox file is loaded. Also no exception should appear, no matter what I click.

**Comment by glandre** [comment]
I noticed that too. I'll take it.

**Comment by sebbrudzinski** [comment]
Fixed by @glandre :)
