### ISSUE TITLE
Add some sort of info about present connection with Dropbox account

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#73]
The application UI should present some sort of check, that displays whether the application is currently authenticated with Dropbox. Since the connection to the Dropbox account is remembered even after the application is reopened, there's no other way to verify if the connection is open, than attempting to open/save some files to Dropbox. We could also display some info about user, for example: "Conected to Dropbox account as <username>".

**Comment by glandre** [comment]
Working on it.

**Comment by glandre** [comment]
OK @sebbrudzinski, I've refactored the code. I think that organizing all Status' information in an Enum made the code much more elegant. Thank you.
Please, see if you have any more suggestion.

**Comment by sebbrudzinski** [comment]
Looks great now, I've merged the changes. I think I'll add the info about used images in the help -> about window. Thanks, @glandre
