### ISSUE TITLE
Find LaTeX distribution directory asks for confirmation upon "Cancel"

### ISSUE THREAD

**Issue by LordFarin** [sebbrudzinski/Open-LaTeX-Studio#78]
During the initial setup of this project I ran into the first issue already.

When selecting the LaTeX directory from the options menu, hitting Cancel will bring up the confirmation popup for the pdflatex package not being found.

This seems undesirable because Cancel should always close the dialogue.

**Comment by sebbrudzinski** [comment]
Fixed in https://github.com/sebbrudzinski/Open-LaTeX-Studio/commit/3020eeb7d383044be931682f76ae684baf977f68
