### ISSUE TITLE
Revision Display is not cleaned when another file is opened from Dropbox

### ISSUE THREAD

**Issue by glandre** [sebbrudzinski/Open-LaTeX-Studio#87]
Repro steps:
- With an already opened file (which is stored in Dropbox), notice the Revisions List
- Open a different file from Dropbox via "Open from Dropbox"
- The Revisions List is updated with the revisions of the lastly opened file
- However, the Revision Display keeps opened with the last revision being displayed
- **Notice** that, because of that, it is possible to restore that revision (which is related to an already closed file) to the recently opened file.

Expected behavior: when a different file is opened (or even created), the Revisions Display should be cleaned and closed.

**Comment by WhiteHsu** [comment]
@glandre 
I'm interested in this item and trying to reproduce this issue but not sure if my reproducing steps are correct or not. The following are my steps and please kindly help confirm if I have any incorrect understanding:

1. Open a file "TestFile01" from Dropbox.
![pic01](https://cloud.githubusercontent.com/assets/7831418/14523448/68b5ad70-0266-11e6-9c8f-0329555afa8b.png)

2. Select the "View Revision" below to open the revision file of "TestFile01".
![pic02](https://cloud.githubusercontent.com/assets/7831418/14523483/8d043034-0266-11e6-8334-c30409b8117e.png)

3. Select "Open from Dropbox" again and select the other file "TestFile02" from Dropbox:
![pic03](https://cloud.githubusercontent.com/assets/7831418/14523614/2d6fbdc2-0267-11e6-80b4-a8211edd5afd.png)

4. Then the file "TestFile02" will be launched but the old revision file of "TestFile01" will be still opened and launched as well:
![pic04](https://cloud.githubusercontent.com/assets/7831418/14523654/61d9882c-0267-11e6-8cd7-7d65bdf674e9.png)

So do you mean that on the Step 4 above, after opening new file from Dropbox, the old revision file of "TestFile01" should be closed and cleared? Do I understand correctly?

**Comment by sebbrudzinski** [comment]
@WhiteHsu This issue has aready been worked on and is awaiting approval in the pull requests: https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/89

**Comment by glandre** [comment]
Hey guys,

I'm sorry for my absence these days. I started working on a new project at
work  so I am still getting used to my new routine. I will take a look at
the pull request ASAP.

Bests,
Geraldo
Em 14/04/2016 13:06, "Sebastian Brudziński" <notifications@github.com>
escreveu:

**Comment by glandre** [comment]
Solved by @sebbrudzinski!
