### ISSUE TITLE
Add generic settings change provider

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#90]
There's currently no easy and pretty way to listen to settings change in Open LaTeX Studio. One of the workarounds is registering your own PropertyChangeListeners to react to changed settings. Since the publisher-subscriber model will most likely be useful with many other settings, we should look into implementing a nice, generic way to subscribe to chosen/all properties change events.

**Comment by LordFarin** [comment]
I've been looking into this article: https://dzone.com/articles/better-data-binding-model.
The ideas behind it seem sound but I haven't translated it to the context of Open LaTeX Studio yet.

**Comment by sebbrudzinski** [comment]
It seems quite promising to me. Looks like a nice and clean solution. I have only glanced through the article, but do you know if it would be possible to subscribe to a certain property change, rather than just PropertyChangeEvent? If not, every listener would be responsible for checking which property was modified and take action only if the property of the interest was changed.

**Comment by LordFarin** [comment]
I ended up reading a lot more about all that comes with settings management, listeners in Java, and more things. In the end I came up with a mechanism that:
* Bundles all the settings in a sub-enum of ApplicationSettings as the single source of truth;
* Connectedly, obfuscates the storage name of all settings;
* Uses the annotation @SettingListener to identify the methods that are supposed to handle changes in a particular setting;
* Simplifies registering a class as listening to settings through one call to ApplicationSettings.registerSettingListeners.

The implementation (which uses a moderate amount of reflection) can be seen in my forked master branch: https://github.com/LordFarin/Open-LaTeX-Studio. Note that it is some commits behind your master branch.

If this new approach is to your liking, we need to look into some compiler verification of the annotation (to make sure that the signature of the annotated method is appropriate) as well as start using the SettingType enum to handle settings better.

**Comment by sebbrudzinski** [comment]
@LordFarin I've reviewed the code and I like the approach. I was even thinking of making it even more generic - not only as a settings listener, but the generic publisher-subscriber implementation of the Open LaTeX Studio. Of course we couldn't avoid reflections, but it doesn't bother me much. 

Honestly, I wouldn't bother with verifications of the method signature at a compile time. I'd just javadoc the annotation properly and name it a contract of this annotation. If the contract is not fulfiled, we can just ignore the annotated method.

**Comment by sebbrudzinski** [comment]
Thank You @LordFarin! This was a big challenge and I'm happy we have managed to get the first version of the settings change provider working. I'll close this ticket as resolved now, but feel free to open new ones for the remaining work and/or new ideas.
