### ISSUE TITLE
Add ability to disable auto-complete popovers

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#91]
Since we already support changing the delay time for auto-complete popovers, we may also add the ability to disable the popovers at all. Some people may find them unnecessary or annoying and might want to turn them off. On UI, this should be a simple checkbox next to the auto-complete delay setting.

**Comment by sabbir044** [comment]
Going to implement it :D.

**Comment by sebbrudzinski** [comment]
Fixed by @sabbir044
