### ISSUE TITLE
Document the process of submitting LaTeX templates to Open LaTeX Studio

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#99]
#27 added the ability to use LaTeX templates in Open LaTeX Studio. The implemented solution made it easy to add more templates - all that must be done is putting the .tex template file in the correct directory and adding metadata about that template in the xml file. We should document that process on our wiki, so less technical contributors can submit their templates easily.

**Comment by andyzen619** [comment]
Hi sebbrudzinski,

I am new to open source and Git Hub and thought that updating the wiki would be a good place to start. I am confused as to whether I have to submit a pull request for the wiki update or if I just create a new page and save it.

Thanks,
Andy

**Comment by sebbrudzinski** [comment]
Hello @andyzen619 

Please go ahead and create a new page :)

**Comment by andyzen619** [comment]
Okay done. Let me know if there anything is wrong.  I look forward to contributing to this project in the future :)

**Comment by sebbrudzinski** [comment]
@andyzen619 It looks good. I did some formatting improvements. Can you also add a note to always get author's permission first, before adding the template?

**Comment by andyzen619** [comment]
Okay done. I added the note on the bottom.

**Comment by sebbrudzinski** [comment]
Fixed by @andyzen619  Thanks!
